version: '3.1'

services:
  mongodb:
    image: mongo:latest
    container_name: my-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass123
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data: