version: '3.1'

services:
  pdfcreator:
      build: 
        context: .
        dockerfile: Dockerfile.dev 
      ports:
        - "5000:5000"
      links:
        - mongodb
      volumes:
        - .:/home/app
      environment:
        PORT: 5000
        SECRETKEY: 'b4bf4b771da17d23fe4f8d10f52e2576ecf7dd19'
        FRONTEND: 'http://localhost:4200'
        URL_DB: 'mongodb://admin:pass123@mongodb:27017'
        SMTP_SERVER: "smtp.gmail.com"
        SMTP_PORT: 587
        SMTP_USER: "codingproactive@gmail.com"
        SMTP_PASSWORD: "ymao dqaf cldh mvxj"
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass123
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data: